apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: intent-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/shidina/intent-server:v1
          ports:
            - containerPort: 5050