apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: humidity-sensor
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/shidina/humidity-sensor:v1
          ports:
            - containerPort: 3000