apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proxy-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/shidina/proxy-server:v1
          ports:
            - containerPort: 8080