apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aggregator
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/shidina/aggregator:v1
          ports:
            - containerPort: 3000