apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: humidifier-microservice
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/shidina/humidifier-microservice:v1
          ports:
            - containerPort: 3000